### ISSUE TITLE
寮生issue決めるよー

### ISSUE THREAD

**Issue by fuu38** [RAINeko256/Madorun#1]
・タスクを具体的に文字に起こす
・そのタスクを振り分ける 
@RAINeko256 
@plmwa

**Comment by Chahaaaaan** [comment]
とりあえずはこのツリーにコメントでぶら下げてください

**Comment by hakuyou00** [comment]
テストー

**Comment by RAINeko256** [comment]
とりあえず
・仕様を決める
・HTML,CSS,JavaScriptを勉強する
・Gitを使える環境を用意しておく
こんなところでしょうか
