### ISSUE TITLE
移動ボタンをタップされた際に実行される,上に移動させる関数の作成

### ISSUE THREAD

**Issue by RAINeko256** [RAINeko256/Madorun#7]
### 場所
js/front.js (フォルダ,ファイルが無い場合は新規作成)

### 仕様

**名前**

 furniture_move_up

**引数**

furniture_name : 家具（画像）のid名

 **戻り値**

void(なし)

### 仕事
- ボタン(id : move_up)をタップした時に画像(furniture_name)の座標の値を変化させる関数を作る
- タップされるごとに上向きに座標の値が1ずつ変化するようにする

### 参考文献
- タッチイベントについて
https://qiita.com/strpyth/items/338890abe829de81d402
- 画像の座標の変更について
https://original-game.com/introduction-to-javascript-display-and-move-img/

**Comment by fuu38** [comment]
やります

**Comment by fuu38** [comment]
@RAINeko256 
ボタンが押されたときに、選択されてるオブジェクトのidを引数としてこの関数が呼ばれるって認識で合ってますか
あと座標はpxでいい？

**Comment by RAINeko256** [comment]
その認識であっています.
座標の値は1ずつ動かすって仕事に書いてあります...
今後のissueで動かす量は変数に変えたいと思います...

**Comment by fuu38** [comment]
仕様読んでなくてごめんなさい...
現在の仕様だと上下どちらかにしか動かせないので、上下で関数を分けるか変数にしてから進めるべきかなと

**Comment by RAINeko256** [comment]
座標の値はCSSで指定されていて,上下に動かす際はJSからCSSを直接いじってyの値を変化させると思うのでとりあえずは±1されるようにしてくれると動きがわかるので良いと思っています👍

**Comment by RAINeko256** [comment]
あっそうか上下で分けないといけないんだった...

**Comment by RAINeko256** [comment]
if文でなんとかならない？（適当）

**Comment by fuu38** [comment]
無理かなぁ
上ボタンなのか下ボタンなのかの情報を引数として取らないとたぶんきびしいので。

**Comment by RAINeko256** [comment]
ごめんなさい...issueを二つ追加します...
